# Generated by Django 4.0.3 on 2022-07-22 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('details', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='grade',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
